onDetect:
  command: ''
  action: WARN
messages:
  player-message: '&4Advertising is prohibited.'
  moderator-message: '&c{player} tried to say the following: &4{message}'
  kick-message: '&cKicked for advertising'
  kick-broadcast: '&c{player} was kicked for advertising'
  stealth-mode-command: '&cAn internal error occurred while attempting to perform this command.'
whitelist:
  - 127.0.0.1
  - 0.0.0.0
  - bukkit.org
  - minecraft.net
  - minecraftwiki.net
absolute-whitelist: []
blacklist:
  - SomeOtherCraft
  - Join my server
checks:
  domains: true
  ips: true
  blacklist: true
monitor:
  chat: true
  commands: true
  signs: true
  books: true
debug: false
stealth-mode: false
config-version: 1