name: AntiAdvertiser
version: 1.1-dev
main: net.unknownmc.antiadvertiser.AntiAdvertiser
description: AntiAdvertiser is a configurable plugin that lets you keep your players.
permissions:
  antiadvertiser.bypass:
    children:
      antiadvertiser.bypass.ip: true
      antiadvertiser.bypass.blacklist: true
      antiadvertiser.bypass.domain: true
    default: op
  antiadvertiser.notify:
    default: op
  antiadvertiser.bypass.ip:
    default: op
  antiadvertiser.bypass.domain:
    default: op
  antiadvertiser.bypass.blacklist:
    default: op